Added nx to workspace (#1905)
* Added nx to workspace

* fix test runs

* try different approach for test

* another approach

* set correct default base

* try origin/master

* fetch depth 0

* remove ci and code-coverage options

* Add cleanup logic to ws subscription providers
Only run playwright tests for linux environments
Added link to variable doc

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -15,10 +15,13 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
     - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
     - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
+    - uses: nrwl/nx-set-shas@v2
     - name: restore lerna
       uses: actions/cache@v2
       with:
@@ -37,12 +40,12 @@ jobs:
     - name: Run headless test
       uses: GabrielBB/xvfb-action@v1
       with:
-        run: |
-          # Retry 3 times before the steps actually fails
-          (echo "===== Headless Tests Attempt: 1 ====" && yarn test:ci) || \
-          (echo "===== Headless Tests Attempt: 2 ====" && yarn test:ci) || \
-          (echo "===== Headless Tests Attempt: 3 ====" && yarn test:ci) || \
-          (echo "==== Headless Tests Step Failed ====" && exit 1)
+        run: yarn test:ci:retries
+        # run: |
+        #   (echo "===== Headless Tests Attempt: 1 ====" && yarn test:ci) || \
+        #   (echo "===== Headless Tests Attempt: 2 ====" && yarn test:ci) || \
+        #   (echo "===== Headless Tests Attempt: 3 ====" && yarn test:ci) || \
+        #   (echo "==== Headless Tests Step Failed ====" && exit 1)
     # https://github.com/tanshuai/electron-playwright-e2e-test-quick-start/blob/1e2c653bc2d0af85d98de1c58e56a888f17fe671/.github/workflows/ci.yml#L39-L44
     - name: Upload Test Results 🗃
       if: always()
